version: '3'

services:
  app:
    build: ./web
    volumes:
      - ./app:/var/www
      - ./web/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8081:80"
    working_dir: /var/www
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: LaravelDB
      MYSQL_ROOT_PASSWORD: password